import { mkdir, mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import {
  checkPromptArtifacts,
  generatePromptArtifacts,
  loadPromptDefinitions,
  renderPromptDocs,
  renderRuntimePrompt
} from '../scripts/prompt-generation.mjs';

const promptDefinition = {
  id: 'shadow-system-prompt',
  title: 'Shadow System Prompt',
  sourcePath: 'prompts/shadow-system-prompt.json',
  docsPath: 'docs/prompts/shadow-system-prompt.md',
  runtimePath: 'shadow-agent/src/inference/prompts.ts',
  runtimeExportName: 'SHADOW_SYSTEM_PROMPT',
  purpose: ['Interpret agent activity as concise JSON.'],
  designPrinciples: [
    {
      title: 'Read-only posture',
      body: 'The shadow observes the agent and never suggests actions.'
    }
  ],
  promptSections: [
    {
      heading: 'Opening',
      language: 'text',
      content: 'You are Shadow.\n\nReturn JSON only.',
      commentaryTitle: 'Why this exists',
      commentary: 'Establishes identity and output format.'
    }
  ],
  contextPacket: {
    description: 'User message attached to the system prompt.',
    template: 'Session: {{sessionId}}\nEvents: {{recentEvents}}',
    commentaryTitle: 'Packet contract',
    commentary: 'Keeps runtime event context separate from the system prompt.'
  },
  iterationLog: [
    {
      date: '2026-05-27',
      change: 'Restored generated prompt artifacts.',
      reason: 'Prevent documentation/runtime drift.'
    }
  ]
};

async function makeFixtureRoot() {
  const root = await mkdtemp(join(tmpdir(), 'shadow-prompts-'));
  const sourcePath = join(root, 'prompts', 'shadow-system-prompt.json');
  await mkdir(join(root, 'prompts'), { recursive: true });
  await writeFile(sourcePath, JSON.stringify(promptDefinition, null, 2));
  return root;
}

describe('prompt artifact generation', () => {
  it('loads prompt definitions from canonical JSON files', async () => {
    const root = await makeFixtureRoot();

    const definitions = await loadPromptDefinitions(join(root, 'prompts'));

    expect(definitions).toHaveLength(1);
    expect(definitions[0].id).toBe('shadow-system-prompt');
    expect(definitions[0].promptSections[0].content).toContain('You are Shadow');
  });

  it('renders docs and runtime prompt artifacts from one definition', () => {
    const docs = renderPromptDocs(promptDefinition);
    const runtime = renderRuntimePrompt(promptDefinition);

    expect(docs).toContain('# Shadow System Prompt');
    expect(docs).toContain('> Generated from `prompts/shadow-system-prompt.json`.');
    expect(docs).toContain('## Full Prompt');
    expect(docs).toContain('You are Shadow.');
    expect(runtime).toContain('This file is generated by `npm run prompts:generate`.');
    expect(runtime).toContain('export const SHADOW_SYSTEM_PROMPT = `You are Shadow.');
  });

  it('reports stale artifacts until generation rewrites them', async () => {
    const root = await makeFixtureRoot();
    await mkdir(join(root, 'docs', 'prompts'), { recursive: true });
    await mkdir(join(root, 'shadow-agent', 'src', 'inference'), { recursive: true });
    await writeFile(join(root, 'docs', 'prompts', 'shadow-system-prompt.md'), 'stale docs');
    await writeFile(join(root, 'shadow-agent', 'src', 'inference', 'prompts.ts'), 'stale runtime');

    await expect(checkPromptArtifacts({ root })).resolves.toEqual([
      'docs/prompts/shadow-system-prompt.md',
      'shadow-agent/src/inference/prompts.ts'
    ]);

    const results = await generatePromptArtifacts({ root });

    expect(results).toEqual([
      {
        id: 'shadow-system-prompt',
        docsChanged: true,
        runtimeChanged: true,
        docsPath: 'docs/prompts/shadow-system-prompt.md',
        runtimePath: 'shadow-agent/src/inference/prompts.ts'
      }
    ]);
    await expect(checkPromptArtifacts({ root })).resolves.toEqual([]);
    await expect(readFile(join(root, 'docs', 'prompts', 'shadow-system-prompt.md'), 'utf8')).resolves.toContain(
      'Generated from `prompts/shadow-system-prompt.json`.'
    );
  });

  it('treats CRLF checkout line endings as current artifacts', async () => {
    const root = await makeFixtureRoot();
    await generatePromptArtifacts({ root });

    for (const artifactPath of [
      join(root, 'docs', 'prompts', 'shadow-system-prompt.md'),
      join(root, 'shadow-agent', 'src', 'inference', 'prompts.ts')
    ]) {
      const content = await readFile(artifactPath, 'utf8');
      await writeFile(artifactPath, content.replace(/\n/g, '\r\n'));
    }

    await expect(checkPromptArtifacts({ root })).resolves.toEqual([]);
  });
});
